name: pangeo-bench
channels:
  - conda-forge
dependencies:
  - click
  - dask-jobqueue>=0.8.0
  - dask-labextension
  - dask>=2022.7.1
  - fsspec>=0.7.3
  - holoviews
  - hvplot
  - ipywidgets
  - jupyterlab
  - matplotlib
  - netcdf4
  - nodejs
  - numpy
  - pandas
  - python=3.9
  - s3fs>=0.4.2
  - scipy
  - setuptools
  - xarray>=0.15.1
  - zarr
